### ISSUE TITLE
ModuleNotFoundError: No module named 'baseapi'

### ISSUE THREAD

**Issue by LazyHippogriff** [jameswenzel/BaseAPI#2]
I had installed this module by using the following command:

> python3.6 -m pip install baseapi --user

pip show baseapi gives the following output:
```
Name: BaseAPI
Version: 0.1.1
Summary: A base class for implementing an HTTP API wrapper
Home-page: https://github.com/jameswenzel/BaseAPI
Author: James Wenzel
Author-email: wenzel.james.r@gmail.com
License: Apache License 2.0
Location: /home/ec2-user/.local/lib/python3.6/site-packages
Requires: requests
Required-by:
```

however I'm getting ModuleNotFoundError when I import baseapi.

```
[ec2-user@test]$ python3.6
Python 3.6.3 (default, Apr 28 2019, 08:05:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import baseapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'baseapi'
>>> import sys
>>> sys.path
['', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/home/ec2-user/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages']

```

Basically I need to use `txfcm` but I've not been able to use it because of this issue.

**Comment by emo-eth** [comment]
Hi Vishal, I mainly set up this project for personal use. Glad you're interested, but I can't guarantee it will be useful outside of the couple API wrappers I've made that extend this class.
That being said, I believe the import is case-sensitive, so give `import BaseAPI` a try.
